language: python
python:
    - "3.6"

sudo: false

install:
    - pip install pytest
    - pip install pytest-cov
    - pip install coveralls

script:
    - pytest --cov=gol

after_success:
    - coveralls

