language: python
python:
    - "3.6"

sudo: false

install:
    - pip install pytest
    - pip install pytest-cov
    - pip install coveralls

script:
    - pytest --cov=gol/
    - pytest --cov=gol/ gol/test/
#    - pytest --cov=gol/ gol/test/test.py
    - pytest --cov=gol/ gol.test
    - pytest --pyargs gol
#    - pytest gol/test/test.py
    - pytest gol/test/

after_success:
    - coveralls

